name: Tier3 workflow
on: 
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
jobs: 
    get_code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout_code
          uses: actions/checkout@v4
        - name: setup environment
          uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
        - name: setup virtual environment
          run: |
            python3 -m venv venvtier3
            source venvtier3/bin/activate
        - name: cache depnedencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        - name: install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install flask
        

    Build:
      needs: get_code
      runs-on: ubuntu-latest
      steps:
        - name: checout code
          uses: actions/checkout@v4
        - name: setup environment
          uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
        - name: setup virtual environment
          run: |
            python3 -m venv venvtier3
            source venvtier3/bin/activate
        - name: cache depnedencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        - name: install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install flask
        - name: run applications
          run: |
            python3 app.py &
            python3 services.py &
            python3 models.py &

    Test:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - name: checout code
          uses: actions/checkout@v4
        - name: setup environment
          uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
        - name: setup virtual environment
          run: |
            python3 -m venv venvtier3
            source venvtier3/bin/activate
        - name: cache depnedencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        - name: install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install flask
        - name: first test
          continue-on-error: true
          id: Test_1
          run: |
            python3 test_tier3_1.py > test_result.txt 2>&1
        - name: second test
          continue-on-error: true
          id: Test_2
          run:
            python3 test_tier3_2.py >> test_result.txt 2>&1
        - name: get artifacts
          uses: actions/upload-artifact@v4
          with:
            name: message from the test result
            path: test_result.txt
        - name: get failures test_1
          if: steps.Test_1.outcome == 'failure'
          run: echo "❌ test_tier3_1.py failed"
        - name: get failure test_2
          if: steps.Test_2.outcome == 'failure'
          run: echo "❌ test_tier3_2.py failed"
        


          
            


        


